- name: INSTALLING THE GIT SERVER
  hosts: web
  become: yes
  tasks:
  - name: INSTALLING NGINX SERVER
    ansible.builtin.yum:
     name: nginx
     state: present
  
  - name: STARTING THE NGINX SERVER
    ansible.builtin.service:
     name: nginx
     state: started
    