---
- name: INSTALLING HTTPD SERVER
  hosts: web
  become: yes
  vars:
    package: maven
  tasks:
    - name: INSTALLING "{{ PACKAGE }}"" USING VARIABLES
      ansible.builtin.yum:
        name: "{{ package }}"
        state: present
