- name: INSTALLING PACKAGE FROM VARIABLE FILE
  hosts: web
  become: yes
  vars_files:
   - variable.yaml
  tasks:
   - name: INSTALLING PACKAGE FROM VARIABLE FILE
     ansible.builtin.yum:
      name: "{{package}}"
